version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:app
    container_name: WebsiteApp
    depends_on:
      - db
    command: bash -c "cd /app/src && pipenv run ./manage.py runserver 0.0.0.0:8000"
    # command: pwd
    # command: bash -c "pwd && cd /app/src && pwd && ls -la"
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - PGDATA=/var/lib/pg_data
    container_name: Postgres
