services:
  app:
    build: .
    volumes:
      - .:/src
    ports:
      - 8000:8000
    image: app:app
    container_name: WebsiteApp
    depends_on:
      - db
    # command: pipenv run ./manage.py runserver 0.0.0.0:8000
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - PGDATA=/var/lib/pg_data
    container_name: Postgres
